/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.5/samples
 */
plugins {
    java
}

group = "com.priyakdey"
version = "0.0.1"

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

val ENABLE_PREVIEW = "--enable-preview"

tasks.withType<JavaCompile> {
    options.compilerArgs.add(ENABLE_PREVIEW)
}

tasks.withType<JavaExec> {
    jvmArgs(ENABLE_PREVIEW)
}